from pydantic import BaseModel, Field
from typing import Optional, Literal

# Type definitions matching frontend
Audience = Literal["technical", "business", "academic", "general"]
Template = Literal[
    "corporate", "academic", "startup", "minimal",
    "creative", "nature", "futuristic", "luxury"
]
DeckStatus = Literal["outline", "analyze", "content", "charts", "optimize", "layout", "design", "images", "adjust", "review", "done", "error"]


class DeckRequest(BaseModel):
    """Request model for creating a new deck."""
    prompt: str = Field(..., min_length=1, max_length=500, description="The presentation topic")
    slideCount: int = Field(..., ge=5, le=30, description="Number of slides to generate")
    audience: Audience = Field(..., description="Target audience")
    template: Template = Field(..., description="Presentation template style")

    class Config:
        json_schema_extra = {
            "example": {
                "prompt": "AI in Healthcare: Transforming Patient Care",
                "slideCount": 10,
                "audience": "business",
                "template": "corporate"
            }
        }


class DeckResponse(BaseModel):
    """Response model for deck creation."""
    deckId: str = Field(..., description="Unique identifier for the deck")
    status: DeckStatus = Field(..., description="Current generation status")
    message: Optional[str] = Field(None, description="Optional status message")


class DeckStatusResponse(BaseModel):
    """Response model for deck status inquiry."""
    deckId: str = Field(..., description="Unique identifier for the deck")
    status: DeckStatus = Field(..., description="Current generation status")
    progress: Optional[int] = Field(None, ge=0, le=100, description="Progress percentage")
    currentStep: Optional[str] = Field(None, description="Human-readable current step")
    error: Optional[str] = Field(None, description="Error message if status is error")

    class Config:
        json_schema_extra = {
            "example": {
                "deckId": "550e8400-e29b-41d4-a716-446655440000",
                "status": "render",
                "progress": 75,
                "currentStep": "Generating slide 8 of 10"
            }
        }


class SlideLayoutResponse(BaseModel):
    """Layout instructions for a slide."""
    layout_idx: int = Field(..., description="python-pptx slide layout index (0-8)")
    visual_elements: list[dict] = Field(default_factory=list, description="Additional shapes/images to add")
    notes: Optional[str] = None


class TableData(BaseModel):
    """Model for table content."""
    headers: list[str]
    rows: list[list[str]]


class SlideContent(BaseModel):
    """Model for individual slide content."""
    title: str
    content: list[str] = Field(default_factory=list, description="Bullet points")
    paragraph: Optional[str] = Field(None, description="Detailed paragraph text for narrative slides")
    table: Optional[TableData] = Field(None, description="Structured table data")
    image_description: Optional[str] = Field(None, description="Description of an image to include")
    image_url: Optional[str] = Field(None, description="URL of the image to embed")
    background_image_url: Optional[str] = Field(None, description="URL of the background image")
    chart_url: Optional[str] = Field(None, description="Path to generated chart image")
    chart_type: Optional[str] = Field(None, description="Type of chart: bar, line, pie, area, scatter")
    layout_type: Optional[str] = Field(None, description="Template layout type: bullet_points, narrative, table_data, two_column, comparison, image_content, chart_data, quote, timeline, etc.")
    slideType: Literal["title", "content", "comparison", "data", "table", "image", "narrative"] = "content"
    layout: Optional[SlideLayoutResponse] = None # Added layout info
    notes: Optional[str] = None
    content_role: Optional[Literal["outline", "detail", "summary"]] = Field(None, description="Role of the slide: outline (use bullet points), detail (use paragraph), or summary (use table)")
    layout_adjustments: Optional[dict] = Field(default_factory=dict, description="Layout adjustment hints from LayoutAdjustmentAgent")



class OutlineSection(BaseModel):
    """Model for a section in the hierarchical outline."""
    title: str
    description: str
    weight: int = Field(..., ge=1, le=10, description="Importance/Complexity weight 1-10")
    key_points: list[str]
    suggested_layouts: Optional[list[str]] = Field(default_factory=list, description="Suggested layout types for slides in this section")


class DeckOutline(BaseModel):
    """Model for deck outline generated by OpenAI."""
    title: str
    sections: list[OutlineSection]
